# Generated by Django 5.0.1 on 2024-06-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='items_supplied',
            field=models.ManyToManyField(related_name='suppliers', to='inventory_supplier.item'),
        ),
    ]
