# Generated by Django 5.0.1 on 2024-06-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_supplier', '0002_alter_supplier_items_supplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='items_supplied',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='inventory_supplier.item'),
        ),
    ]
